config/routes.rb
Rails.application.routes.draw do
  devise_for :fighters
  resources :fights
  get 'home/profile'
  root "home#index"
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fight.rb
class Fight < ApplicationRecord
    # this line sets teh relationship for the fights to the fighters
    belongs_to :fighter, :optional => true
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :fights

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #this code was taken from the devise github page and allows me to add more filds for registration
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:club, :role])
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action  :checkUser
  before_action :set_fight, only: %i[ show edit update destroy ]
  before_action :authenticate_fighter!, except: [ :index]
  #calls the function "fighterbefor the action of edit,update,destroy
 before_action :fighter_check, only: [:edit, :update, :destroy]
 
 #send to home page if not logged in
def checkUser
  redirect_to root_path, notice: "not logged in" if current_fighter.nil?
end

  def index
   
    #ransakc search
   @q= Fight.ransack(params[:q])
     @fights = @q.result
    
  end

  # GET /fights/1 or /fights/1.json
  def show
  end

  # GET /fights/new
  def new
    @fight = current_fighter.fights.build
  end

  # GET /fights/1/edit
  def edit
  end

  # POST /fights or /fights.json
  def create
    #@fight = Fight.new(fight_params)
    @fight=current_fighter.fights.build(fight_params)

    respond_to do |format|
      if @fight.save
        format.html { redirect_to fight_url(@fight), notice: "Fight was successfully created." }
        format.json { render :show, status: :created, location: @fight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end

  # takes current ussers finds its id and comapres it to the fight fighterid by it also allows coaches to edit update and delete there fighters figths
  #also attempted to make it possible nfor only coaches to eddit the fights that came from there clubs fighters instead i only make them available in the ui
 def fighter_check
      
      @fight = current_fighter.fights.find_by(id: params[:id])
     #@fight1= current_fighter.fights.find_by(club: params[:club])
     
      redirect_to root_path, notice: "not your fight ayeee?" if @fight.nil? 
  end

  # PATCH/PUT /fights/1 or /fights/1.json
  def update
    respond_to do |format|
      if @fight.update(fight_params)
        format.html { redirect_to fight_url(@fight), notice: "Fight was successfully updated." }
        format.json { render :show, status: :ok, location: @fight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fight.errors, status: :unprocessable_entity }
      end
    end
  end
  
 
  # DELETE /fights/1 or /fights/1.json
  def destroy
    @fight.destroy

    respond_to do |format|
      format.html { redirect_to fights_url, notice: "Fight was successfully destroyed." }
      format.json { head :no_content }
    end


  end

   
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fight_params
      params.require(:fight).permit(:blue_corner, :red_corner, :date, :competition, :winner, :fighter_id, :club)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def connection
    require('logger')
    @connection = Faraday.new(
      url: 'https://newsapi.org/v2/',
    ) do |faraday|
      faraday.response(:logger, ::Logger.new($stdout), bodies: true)
    end
  end
  
  def index
    response = connection.get(
      'everything'
    ) do |req|
      req.headers['Content-Type'] = 'application/json'
      req.params = { 
        apiKey: '983ae5e979cd49258f0d9b577d7f5847',
        sortBy: 'publishedAt',
        from: Time.now.strftime("%Y-%m-%d"),
        q: 'boxing'
     }
    end
    @articles = JSON.parse(response.body, symbolize_names: true)[:articles]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/fights/_fight.html.erb
<div id="<%= dom_id fight %>"clas="card" style="width: 18rem;"> 
  <<li class="list-group-item">
    <strong>Blue corner:</strong>
    <%= fight.blue_corner %>
  </li>

 <li class="list-group-item">
    <strong class=>Red corner:</strong>
    <%= fight.red_corner %>
  </li>

  <li class="list-group-item">
    <strong>Date:</strong>
    <%= fight.date %>
  </li>

  <li class="list-group-item">
    <strong>Competition:</strong>
    <%= fight.competition %>
  </li>

  <li class="list-group-item">
    <strong>Winner:</strong>
    <%= fight.winner %>
  </li>

</div>

app/views/fights/_form.html.erb
<%= form_with(model: fight) do |form| %>
  <% if fight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fight.errors.count, "error") %> prohibited this fight from being saved:</h2>

      <ul>
        <% fight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
      <%= form.text_field :blue_corner, autocomplete: "blue_corner",class: 'form-control', autocomplete: "blue_corner", placeholder: 
    "Blue corner fighter" %>
  </div>
<br/>
 <div>
      <%= form.text_field :red_corner, autocomplete: "red_corner",class: 'form-control', autocomplete: "red_corner", placeholder: 
    "Red corner fighter" %>
  </div>
<br/>
  <div>
      <%= form.date_field :date, autocomplete: "date",class: 'form-control', autocomplete: "date_corner", placeholder: 
    "Date" %>
  </div>
 <br/>
  <div>
       <%= form.text_field :competition, autocomplete: "competition",class: 'form-control', autocomplete: "dcompetition_corner", placeholder: 
     "Competition" %>
   </div>
   <br/>
   <p>Winner</p>
    <div>
       <%= form.select :winner, [['Red Corner', 'blue_corner_cont'], ['Blue Corner', 'red_corner_cont']], placeholder: 'Winner', class:"dropdown" %>
   </div>
<br/>

  

<!-- this code sets the id number to the cuirrent usser signed in id -->
    <%= form.number_field :fighter_id, id: :fight_fighter_id, class:"form-control", value: current_fighter.id, type: :hidden%>
    <%= form.text_field :club, club: :fight_club, class:"form-control", value: current_fighter.club, type: :hidden%>
  
    
  
<%=%>
  <div>
    <%= form.submit "Create", class:"btn btn-primary"%>
  </div>
<% end %>

app/views/fights/edit.html.erb
<h1>Editing fight</h1>

<%= render "form", fight: @fight %>

<br>

<div>
  <%= link_to "Show this fight", @fight %> |
  <%= link_to "Back to fights", fights_path %>
</div>

app/views/fights/index.html.erb
<h1>Fight History</h1>

<div >
<%= search_form_for(@q, url: "/fights", method: :get) do |f| %>

  

  <!--Search if the name field contains...-->
 
  <%= f.search_field :blue_corner_or_red_corner_or_competition_cont, class: "input-group-text", placeholder:"search"%>
  
</div>
 
  
 

<div>
  
<% end %>
</div>
<br/>



<table class="table table-striped table-dark">
  <thead>
  <tr>
    <th scope="col">Blue Corner</th>
    <th scope="col"> </th>
    <th scope="col">Red Corner</th>
    <th scope="col">Date</th>
    <th scope="col">Competition</th>
    <th scope="col">Winner</th>
    <th scope="col"></th>
  <tr>
</thead>
  <tbody>
      <% @fights.each do |fight| %>
       
        <tr>
        
          <% 
           if fight.fighter == current_fighter or (current_fighter.role == 'coach' && current_fighter.club == fight.club) %> 
          <td><%= link_to fight.blue_corner, fight %></td>
          <td>vs</td>
          <td><%= fight.red_corner %></td>
          <td><%= fight.date %></td>
          <td><%= fight.competition %></td>
          <td><%= fight.winner %></td>
          
          
          
          
          
          
          <td><%= link_to 'Delete', fight, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          <% end %>
        </tr>
        <% end %>
        
      
    </tbody>
</table>

<%= link_to "New fight", new_fight_path, class:"btn btn-outline-primary"%>

app/views/fights/new.html.erb
<h1>New fight</h1>

<%= render "form", fight: @fight %>

<br>

<div>
  <%= link_to "Back to fights", fights_path %>
</div>

app/views/fights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fight %>

<div>
  <%= link_to "Edit this fight", edit_fight_path(@fight), class:'btn btn-primary'%> |
  <%= link_to "Back to fights", fights_path,class:'btn btn-primary' %>
 
</div>

<div>
  <%= button_to "Destroy this fight", @fight, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid "> 
  <!-- home link to root_path -->
   <%= link_to "boxingApp", root_path,class:"navbar-brand"  %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<% if fighter_signed_in?%>
        <li class="nav-item">
          <%= link_to "Profile", home_profile_path,class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Fights", fights_path,class:"nav-link" %>
        </li>
       
        <li class="nav-item">
          <%= link_to "Log out", destroy_fighter_session_path, 'data-turbo-method': :delete, class:"nav-link"%>
        </li>
        <% else %>

        <li class="nav-item">
          <%= link_to "Sign In", new_fighter_session_path,class:"nav-link" %>
        </li>
       <li class="nav-item">
          <%= link_to "Sign Up", new_fighter_registration_path,class:"nav-link" %>
        </li>
        
      
         
       <%end%>
       
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="card">

    <% @articles.each do |article| %>
    <h2><%= article[:title] %></h2>
    
    <%= link_to "View article", article[:url], class:"btn btn-outline-primary"%>
    <br/>
    <br/>
    <% end %>
</div>
<br/>

app/views/home/profile.html.erb
<div class="container"> 
<div class="card">
  <div class="card-header">
    <%=current_fighter.email %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Details</h5>
    <p class="card-text">Club: <%=current_fighter.club %></p>
    <p class="card-text">Role: <%=current_fighter.role %></p>
    <p class="card-text">Date made: <%=current_fighter.created_at %></p>
    <%= link_to "Edit Account", edit_fighter_registration_path,class:"nav-link" %>
  </div>
</div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-dark alert-dismissible fade show" role="alert">
 <!--this rube code under here gives me the alert.
 the html suronding is for the styling with bootstrap :) -->
  <%=notice%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>boxing test</title>


    
   
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  

  </head>
  <body>
  <%= render 'home/header'%>
  <div class ="container">
<!-- THIS FUNCTION WILL RENDER THE _ALERS.HTML.ERB FILE IF A
NOTICE APPEARS -->
<BR/>
  <% if notice%>
  <%= render 'layouts/alerts'%>
  <%end%>


  <br/>
     <%= yield %>
</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>